name: dewallads

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.20.0
  flutter_carousel_widget: ^2.1.2
  firebase_database: ^10.3.3
  cloud_firestore: ^4.12.2
  intl: ^0.18.1
  geolocator: ^10.0.0
  http: ^1.1.0
  flutter_inappwebview: ^5.8.0
  firebase_auth: ^4.15.2
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  provider: ^6.1.1
  badges: ^3.1.2
  youtube_player_flutter: ^8.1.2
  permission_handler: ^9.1.0
  onesignal_flutter: ^5.0.4
  flutter_custom_carousel_slider: ^1.0.0
  fluttertoast: ^8.2.2
  image_picker: ^1.0.5
  video_player: ^2.8.1
  flutter_ffmpeg: ^0.4.2
  path_provider: ^2.1.1
  path: ^1.8.0
  firebase_storage: ^11.5.6
  video_compress: ^3.1.2
  progress_dialog_null_safe: ^1.0.7
  whatsapp_unilink: ^2.1.0
  url_launcher: ^6.0.6
  font_awesome_flutter: ^9.0.0
  clipboard: ^0.1.3
  webview_flutter: ^4.4.2
  google_sign_in: ^6.2.1
  sign_button: ^2.0.6






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  rename: ^3.0.1

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/images/logo.png"
    min_sdk_android: 24




flutter:


  uses-material-design: true


  assets:
    - assets/
    - assets/images/



  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/RalewayBold.ttf
          weight: 700
        - asset: assets/fonts/RalewayMedium.ttf
          weight: 500
        - asset: assets/fonts/RalewayRomanExtraBold.ttf
          weight: 800
        - asset: assets/fonts/RalewayRegular.ttf
          weight: 400
        - asset: assets/fonts/RalewaySemiBold.ttf
          weight: 600
        - asset: assets/fonts/RalewayRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/RalewayRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/RalewayRomanBold.ttf
          weight: 700
        - asset: assets/fonts/RalewayRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/RalewayExtraBold.ttf
          weight: 800
    - family: Montserrat
      fonts:
        - asset: assets/fonts/MontserratBold.ttf
          weight: 700
        - asset: assets/fonts/MontserratRegular.ttf
          weight: 400
        - asset: assets/fonts/MontserratExtraBold.ttf
          weight: 800
        - asset: assets/fonts/MontserratSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MontserratMedium.ttf
          weight: 500
