// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAUl5NT5WOUqc3Sngq6o7xn99B2ehcQEE',
    appId: '1:325164339395:web:16ee2a65de366470e25276',
    messagingSenderId: '325164339395',
    projectId: 'dewall-7',
    authDomain: 'dewall-7.firebaseapp.com',
    databaseURL: 'https://dewall-7-default-rtdb.firebaseio.com',
    storageBucket: 'dewall-7.appspot.com',
    measurementId: 'G-V26GY2DWDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLaNC4DZUfWYoIEy8pXVNleJcXQsGUtBo',
    appId: '1:325164339395:android:033e68c9884f478ae25276',
    messagingSenderId: '325164339395',
    projectId: 'dewall-7',
    databaseURL: 'https://dewall-7-default-rtdb.firebaseio.com',
    storageBucket: 'dewall-7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlsDYtOSou4MSw6v3xQdva-zXXQwhzuXQ',
    appId: '1:325164339395:ios:0e815c36b0dedd46e25276',
    messagingSenderId: '325164339395',
    projectId: 'dewall-7',
    databaseURL: 'https://dewall-7-default-rtdb.firebaseio.com',
    storageBucket: 'dewall-7.appspot.com',
    androidClientId: '325164339395-vg8fjvjq99vsf5i2k03ji6ngrb8vcsa9.apps.googleusercontent.com',
    iosClientId: '325164339395-aq85u9j6rd77hu21163se68t53d5j9eo.apps.googleusercontent.com',
    iosBundleId: 'com.dewall.dewallads',
  );
}
